# Generated by Django 3.1.1 on 2020-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
